// eval/models.ts
var BENCHMARK_MODELS = [
  {
    id: "smollm2-360m-q4f16",
    name: "SmolLM2 360M Instruct",
    family: "SmolLM2",
    architecture: "llama",
    paramsB: 0.36,
    vramMB: 376,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1", "q0f16", "q0f32"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "ultrafast",
    requiresShaderF16: true,
    downloadUrl: "https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF",
    ggufFilePattern: "Q4_0"
  },
  {
    id: "qwen3-0.6b-q4f16",
    name: "Qwen3 0.6B",
    family: "Qwen3",
    architecture: "qwen",
    paramsB: 0.6,
    vramMB: 1403,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1", "q0f16"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen3-0.6B-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Qwen/Qwen3-0.6B-GGUF"
  },
  {
    id: "llama-3.2-1b-q4f16",
    name: "Llama 3.2 1B Instruct",
    family: "Llama 3.2",
    architecture: "llama",
    paramsB: 1.23,
    vramMB: 879,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1", "q0f16"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Llama-3.2",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Llama-3.2-1B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF"
  },
  {
    id: "qwen2.5-1.5b-q4f16",
    name: "Qwen2.5 1.5B Instruct",
    family: "Qwen2.5",
    architecture: "qwen",
    paramsB: 1.54,
    vramMB: 1630,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen2.5-1.5B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
    ggufFilePattern: "Q4_0"
  },
  {
    id: "smollm2-1.7b-q4f16",
    name: "SmolLM2 1.7B Instruct",
    family: "SmolLM2",
    architecture: "llama",
    paramsB: 1.71,
    vramMB: 1774,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: true,
    downloadUrl: "https://huggingface.co/mlc-ai/SmolLM2-1.7B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Mungert/SmolLM2-1.7B-Instruct-GGUF",
    ggufFilePattern: "Q4_0"
  },
  {
    id: "qwen3-1.7b-q4f16",
    name: "Qwen3 1.7B",
    family: "Qwen3",
    architecture: "qwen",
    paramsB: 1.7,
    vramMB: 2037,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "balanced",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen3-1.7B-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Qwen/Qwen3-1.7B-GGUF"
  },
  {
    id: "hermes-3-llama-3.2-3b-q4f16",
    name: "Hermes 3 Llama 3.2 3B",
    family: "Hermes 3",
    architecture: "llama",
    paramsB: 3.21,
    vramMB: 2264,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Llama-3.2",
    contextLength: 4096,
    tier: "balanced",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Hermes-3-Llama-3.2-3B-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/bartowski/Hermes-3-Llama-3.2-3B-GGUF",
    ggufFilePattern: "Q4_0."
  },
  {
    id: "llama-3.2-3b-q4f16",
    name: "Llama 3.2 3B Instruct",
    family: "Llama 3.2",
    architecture: "llama",
    paramsB: 3.21,
    vramMB: 2264,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Llama-3.2",
    contextLength: 4096,
    tier: "balanced",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Llama-3.2-3B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF",
    ggufFilePattern: "Q4_0."
  },
  {
    id: "qwen2.5-3b-q4f16",
    name: "Qwen2.5 3B Instruct",
    family: "Qwen2.5",
    architecture: "qwen",
    paramsB: 3.09,
    vramMB: 2505,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "balanced",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen2.5-3B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF",
    ggufFilePattern: "Q4_0"
  },
  {
    id: "phi-3.5-mini-q4km",
    name: "Phi-3.5 Mini Instruct (Q4_K_M, fused-forward)",
    family: "Phi",
    architecture: "phi3",
    paramsB: 3.82,
    vramMB: 2520,
    defaultQuant: "q4km",
    availableQuants: ["q4km"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "MIT",
    contextLength: 4096,
    tier: "balanced",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
    ggufUrl: "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF",
    ggufFilePattern: "Q4_K_M"
  },
  {
    id: "qwen3-4b-q4f16",
    name: "Qwen3 4B",
    family: "Qwen3",
    architecture: "qwen",
    paramsB: 4,
    vramMB: 3432,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen3-4B-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/unsloth/Qwen3-4B-GGUF",
    ggufFilePattern: "Q4_0."
  },
  {
    id: "tinyllama-1.1b-chat-q4_0",
    name: "TinyLlama 1.1B Chat v1.0",
    family: "TinyLlama",
    architecture: "llama",
    paramsB: 1.1,
    vramMB: 760,
    defaultQuant: "q0f32",
    availableQuants: ["q0f32"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 2048,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    ggufUrl: "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
  },
  {
    id: "snowflake-arctic-embed-s-q0f32-b4",
    name: "Snowflake Arctic Embed S",
    family: "Arctic Embed",
    architecture: "bert",
    paramsB: 0.033,
    vramMB: 239,
    defaultQuant: "q0f32",
    availableQuants: ["q0f32"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "Apache-2.0",
    contextLength: 512,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/snowflake-arctic-embed-s-q0f32-MLC",
    ggufUrl: "https://huggingface.co/ChristianAzinn/snowflake-arctic-embed-s-gguf",
    ggufFilePattern: "f16"
  },
  {
    id: "snowflake-arctic-embed-m-q0f32-b4",
    name: "Snowflake Arctic Embed M",
    family: "Arctic Embed",
    architecture: "bert",
    paramsB: 0.109,
    vramMB: 539,
    defaultQuant: "q0f32",
    availableQuants: ["q0f32"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "Apache-2.0",
    contextLength: 512,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/snowflake-arctic-embed-m-q0f32-MLC",
    ggufUrl: "https://huggingface.co/ChristianAzinn/snowflake-arctic-embed-m-gguf",
    ggufFilePattern: "f16"
  },
  {
    id: "bge-small-en-v1.5-q0f16",
    name: "BGE Small EN v1.5",
    family: "BGE",
    architecture: "bert",
    paramsB: 0.033,
    vramMB: 240,
    defaultQuant: "q0f16",
    availableQuants: ["q0f16"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "MIT",
    contextLength: 512,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/BAAI/bge-small-en-v1.5",
    ggufUrl: "https://huggingface.co/ChristianAzinn/bge-small-en-v1.5-gguf",
    ggufFilePattern: "fp16"
  },
  {
    id: "bge-large-en-v1.5-q0f16",
    name: "BGE Large EN v1.5",
    family: "BGE",
    architecture: "bert",
    paramsB: 0.335,
    vramMB: 1500,
    defaultQuant: "q0f16",
    availableQuants: ["q0f16"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "MIT",
    contextLength: 512,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/BAAI/bge-large-en-v1.5",
    ggufUrl: "https://huggingface.co/ChristianAzinn/bge-large-en-v1.5-gguf",
    ggufFilePattern: "fp16"
  },
  {
    id: "jina-embeddings-v2-base-en-q0f16",
    name: "Jina Embeddings v2 Base EN",
    family: "Jina Embeddings",
    architecture: "jina-bert-v2",
    paramsB: 0.137,
    vramMB: 320,
    defaultQuant: "q0f16",
    availableQuants: ["q0f16"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "Apache-2.0",
    contextLength: 8192,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/jinaai/jina-embeddings-v2-base-en",
    ggufUrl: "https://huggingface.co/gaianet/jina-embeddings-v2-base-en-GGUF",
    ggufFilePattern: "f16"
  },
  {
    id: "nomic-embed-text-v1.5-q0f16",
    name: "Nomic Embed Text v1.5",
    family: "Nomic Embed",
    architecture: "nomic-bert",
    paramsB: 0.137,
    vramMB: 320,
    defaultQuant: "q0f16",
    availableQuants: ["q0f16"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "Apache-2.0",
    contextLength: 2048,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/nomic-ai/nomic-embed-text-v1.5",
    ggufUrl: "https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF",
    ggufFilePattern: "f16"
  },
  {
    id: "qwen3-embedding-0.6b-hyb",
    name: "Qwen3 Embedding 0.6B (hybrid)",
    family: "Qwen3-Embedding",
    architecture: "qwen3-embedding",
    paramsB: 0.6,
    vramMB: 1100,
    defaultQuant: "hyb",
    availableQuants: ["hyb"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: true },
    license: "Apache-2.0",
    contextLength: 32768,
    tier: "ultrafast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/Qwen/Qwen3-Embedding-0.6B",
    ggufUrl: "https://huggingface.co/Qwen/Qwen3-Embedding-0.6B-GGUF",
    ggufFilePattern: "hyb",
    localGGUFOnly: true
  },
  {
    id: "qwen2.5-coder-1.5b-q4f16",
    name: "Qwen2.5 Coder 1.5B Instruct",
    family: "Qwen2.5 Coder",
    architecture: "qwen",
    paramsB: 1.54,
    vramMB: 1630,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mlc-ai/Qwen2.5-Coder-1.5B-Instruct-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF"
  },
  {
    id: "gemma-2-2b-q4f16",
    name: "Gemma 2 2B IT",
    family: "Gemma 2",
    architecture: "gemma",
    paramsB: 2.61,
    vramMB: 1584,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1", "q4f32_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Gemma",
    contextLength: 4096,
    tier: "fast",
    requiresShaderF16: true,
    downloadUrl: "https://huggingface.co/mlc-ai/gemma-2-2b-it-q4f16_1-MLC",
    ggufUrl: "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF"
  },
  {
    id: "mistral-7b-instruct-v0.3-q4ks",
    name: "Mistral 7B Instruct v0.3",
    family: "Mistral",
    architecture: "mistral",
    paramsB: 7.25,
    vramMB: 4400,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
    ggufUrl: "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF",
    ggufFilePattern: "Q4_K_S"
  },
  {
    id: "mistral-7b-instruct-v0.3-q5km",
    name: "Mistral 7B Instruct v0.3 (Q5_K_M)",
    family: "Mistral",
    architecture: "mistral",
    paramsB: 7.25,
    vramMB: 5400,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
    ggufUrl: "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF",
    ggufFilePattern: "Q5_K_M"
  },
  {
    id: "mistral-7b-instruct-v0.3-q3km",
    name: "Mistral 7B Instruct v0.3 (Q3_K_M)",
    family: "Mistral",
    architecture: "mistral",
    paramsB: 7.25,
    vramMB: 3500,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
    ggufUrl: "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF",
    ggufFilePattern: "Q3_K_M"
  },
  {
    id: "mistral-7b-instruct-v0.3-iq4xs",
    name: "Mistral 7B Instruct v0.3 (IQ4_XS)",
    family: "Mistral",
    architecture: "mistral",
    paramsB: 7.25,
    vramMB: 4200,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
    ggufUrl: "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF",
    ggufFilePattern: "IQ4_XS"
  },
  {
    id: "mistral-nemo-instruct-2407-q4ks",
    name: "Mistral Nemo Instruct 2407 (Q4_K_S, >4 GiB validation)",
    family: "Mistral",
    architecture: "mistral",
    paramsB: 12.25,
    vramMB: 7000,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: false, structuredOutput: false, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
    ggufUrl: "https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF",
    ggufFilePattern: "Q4_K_S"
  },
  {
    id: "llama-3.1-8b-instruct-iq3m",
    name: "Llama 3.1 8B Instruct",
    family: "Llama 3.1",
    architecture: "llama",
    paramsB: 8.03,
    vramMB: 4500,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Llama-3.1",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    ggufUrl: "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
    ggufFilePattern: "IQ3_M"
  },
  {
    id: "qwen3-8b-iq3m",
    name: "Qwen3 8B",
    family: "Qwen3",
    architecture: "qwen",
    paramsB: 8.19,
    vramMB: 4500,
    defaultQuant: "iq3m",
    availableQuants: ["iq3m"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    embeddingCapable: true,
    downloadUrl: "https://huggingface.co/Qwen/Qwen3-8B",
    ggufUrl: "https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF",
    ggufFilePattern: "IQ3_M"
  },
  {
    id: "qwen3-14b-q4ks",
    name: "Qwen3 14B (Q4_K_S, 13B-class registration)",
    family: "Qwen3",
    architecture: "qwen",
    paramsB: 14.77,
    vramMB: 8800,
    defaultQuant: "q4f16_1",
    availableQuants: ["q4f16_1"],
    capabilities: { toolCalling: true, structuredOutput: true, vision: false, embedding: false },
    license: "Apache-2.0",
    contextLength: 4096,
    tier: "quality",
    requiresShaderF16: false,
    downloadUrl: "https://huggingface.co/Qwen/Qwen3-14B",
    ggufUrl: "https://huggingface.co/bartowski/Qwen_Qwen3-14B-GGUF",
    ggufFilePattern: "Q4_K_S"
  }
];
var TIER_ORDER = {
  ultrafast: { order: 0, label: "Ultrafast", speedTarget: "100+ tok/s" },
  fast: { order: 1, label: "Fast", speedTarget: "60+ tok/s" },
  balanced: { order: 2, label: "Balanced", speedTarget: "30+ tok/s" },
  quality: { order: 3, label: "Quality", speedTarget: "20-30 tok/s" }
};
function getModelsByTier() {
  const tiers = new Map;
  for (const model of BENCHMARK_MODELS) {
    const list = tiers.get(model.tier) ?? [];
    list.push(model);
    list.sort((a, b) => a.vramMB - b.vramMB);
    tiers.set(model.tier, list);
  }
  return tiers;
}
function getModelById(id) {
  return BENCHMARK_MODELS.find((m) => m.id === id);
}
function getToolCallingModels() {
  return BENCHMARK_MODELS.filter((m) => m.capabilities.toolCalling);
}
function getEmbeddingModels() {
  return BENCHMARK_MODELS.filter((m) => m.capabilities.embedding);
}
var BROWSER_VRAM_LIMITS = {
  "low-end": { vramGB: 2, maxParamsB: 1, description: "Mobile, old integrated GPUs" },
  midrange: { vramGB: 4, maxParamsB: 3, description: "M1 base, RTX 3060, mid-range laptops" },
  "high-end": { vramGB: 8, maxParamsB: 7, description: "M3/M4 Pro, RTX 4070+" },
  enthusiast: { vramGB: 16, maxParamsB: 14, description: "M4 Max, RTX 4090, desktop workstations" }
};
export {
  getToolCallingModels,
  getModelsByTier,
  getModelById,
  getEmbeddingModels,
  TIER_ORDER,
  BROWSER_VRAM_LIMITS,
  BENCHMARK_MODELS
};
