import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	TokenAttribute,
	type TokenData,
	Tokenizer,
	type TokenizerConfig,
	TokenizerType,
} from "../src/inference/tokenizer.js";

// HF parity regression guard for bug 14b (BERT WordPiece phantom-space
// vocab convention). The TS tokenizer must agree byte-for-byte with HF
// `bert-base-uncased` on the cases generated by
// scripts/generate-bert-golden.py. The vocabulary itself is dumped from
// the real Arctic-Embed-s GGUF by scripts/extract-bert-vocab.ts so this
// test exercises the *post-conversion* phantom-space form, not a
// synthetic stand-in.

interface VocabFixture {
	model: string;
	tokens: string[];
	clsId: number;
	sepId: number;
	unkId: number;
	padId: number;
}

interface GoldenFixture {
	model: string;
	cases: { text: string; ids: number[] }[];
}

const VOCAB_PATH = resolve(
	import.meta.dir,
	"./fixtures/bert-wordpiece-vocab.json",
);
const GOLDEN_PATH = resolve(
	import.meta.dir,
	"./fixtures/bert-wordpiece-golden.json",
);

function readJson<T>(path: string): T {
	return JSON.parse(readFileSync(path, "utf-8")) as T;
}

function makeArcticEmbedTokenizer(): Tokenizer {
	const vocab = readJson<VocabFixture>(VOCAB_PATH);
	const tokens: TokenData[] = vocab.tokens.map((text, i) => ({
		text,
		score: 0,
		// Mark CLS/SEP/UNK/PAD as CONTROL so any future addedTokens scan picks
		// them up; the rest default to NORMAL. The encoder algorithm doesn't
		// use the attr field, so this is purely cosmetic — the CLS/SEP/UNK
		// ids passed below are what actually drive encoding.
		attr:
			i === vocab.clsId ||
			i === vocab.sepId ||
			i === vocab.unkId ||
			i === vocab.padId
				? TokenAttribute.CONTROL
				: TokenAttribute.NORMAL,
	}));
	const cfg: TokenizerConfig = {
		type: TokenizerType.WORDPIECE,
		tokens,
		bpeRanks: new Map(),
		addedTokens: new Map(),
		eosTokenId: vocab.sepId,
		bosTokenId: vocab.clsId,
		padTokenId: vocab.padId,
		vocabSize: tokens.length,
		clsTokenId: vocab.clsId,
		sepTokenId: vocab.sepId,
		unkTokenId: vocab.unkId,
	};
	return new Tokenizer(cfg);
}

const fixturesPresent = existsSync(VOCAB_PATH) && existsSync(GOLDEN_PATH);

describe.skipIf(!fixturesPresent)("WordPiece HF golden parity", () => {
	const tok = fixturesPresent ? makeArcticEmbedTokenizer() : null;
	const golden = fixturesPresent ? readJson<GoldenFixture>(GOLDEN_PATH) : null;

	test("vocab size matches HF bert-base-uncased (30522)", () => {
		expect(tok?.vocabSize).toBe(30522);
	});

	test("special token ids match HF defaults", () => {
		// Tokenizer.config is private; tests peek at it to verify the
		// loader populated the right special-token ids. Cast through
		// unknown to keep the rest of the test type-safe.
		const cfg = (tok as unknown as { config: Record<string, unknown> })?.config;
		expect(cfg?.clsTokenId).toBe(101);
		expect(cfg?.sepTokenId).toBe(102);
		expect(cfg?.unkTokenId).toBe(100);
		expect(cfg?.padTokenId).toBe(0);
	});

	for (const c of golden?.cases ?? []) {
		test(`encode(${JSON.stringify(c.text)}) matches HF`, () => {
			expect(tok?.encode(c.text)).toEqual(c.ids);
		});
	}
});
